### ISSUE TITLE
Ajustar menu

### ISSUE THREAD

**Issue by TiagoGouvea** [Zero40/zero40-wordpress-theme#13]
Foi atualizado o bootstrap e o menu ficou estranho. Em um tamanho ele fica "em linhas" ao invés de se manter na horizontal. Quando fica responsivo a logo e o menu hamburger ficam estranhos também.
A chamado do menu está em `header.php` e utiliza o método `wp_nav_menu` que precisa ser mantido, é mais ver as classes corretas do bootstrap para que as divs fiquem certinhas na exibição.

## Tarefas
- [x] Não permitir que os items quebrem linha
![Home_-_Ecossistema_Empreendedor_de_Juiz_de_Fora](https://user-images.githubusercontent.com/2242549/86765369-75bc1100-c01f-11ea-8819-25cd88238853.png)

- [x] Não deixar o menu ficar horizontal quando menor que 980 pixels
![Home_-_Ecossistema_Empreendedor_de_Juiz_de_Fora_and_wordpress_zero40_–_header_php](https://user-images.githubusercontent.com/2242549/86765460-92f0df80-c01f-11ea-8b90-9d244cac8968.png)

- [x] Quando entrar no responsivo, exibir o menu ao lado da logo, ocupando um pequeno espaço vertical, ao invés de ficar quebrado como está agora
![Home_-_Ecossistema_Empreendedor_de_Juiz_de_Fora_and_wordpress_zero40_–_header_php](https://user-images.githubusercontent.com/2242549/86765629-c6336e80-c01f-11ea-9be1-253cefaabbba.png)

- [x] Não permitir barra do topo cobrir conteúdo
<img width="1188" alt="Zero40" src="https://github.com/Zero40/zero40-wordpress-theme/assets/2242549/b1745ac2-e8da-4d27-8b24-26099238cd8c">

**Comment by viniman** [comment]
@TiagoGouvea resolvi essa issue, mas não consigo dar push na branch criada.

**Comment by TiagoGouvea** [comment]
@viniman Você precisa aceitar o convite que foi pro seu email.

**Comment by viniman** [comment]
Adicionei o PR #31 relacionado a esta issue.
