### ISSUE TITLE
Ajustar CCS do formulário Mailchimp

### ISSUE THREAD

**Issue by TiagoGouvea** [Zero40/zero40-wordpress-theme#4]
O objetivo é facilitar aos visitantes a se inscreverem na maillist do Zero 40, que utiliza o MailChimp. Utilizavamos outro sistema de inscrição em newsletter mais estamos substituindo, então precisamos adequar o estilo do formulário atual.

O mesmo formulário `form-newsletter-mailchimp.php` é incluído na página inicial e em algumas páginas como sitebar.

O formulário já está online e pode ser visto nestas urls
-  https://zero40.com.br/
- https://zero40.com.br/comunidades/

## Tarefas
- [ ] Adequar os estilos para "encaixar" melhor no tema (fontes, cores, margens, etc)
- [ ] Enviar um print aqui na issue pra facilitar a validação se possível

**Comment by fernando-sa** [comment]
Vou resolver essa questão

**Comment by TiagoGouvea** [comment]
Boa @fernando-sa! 💪

**Comment by fernando-sa** [comment]
Fiz alguns ajustes e resolvi alguns dos problemas mais graves do formulário, como o texto não aparecer na tela de comunidades, pelo fundo ser branco e os checkbox de "Quem é você" estarem desordenados. 

De mudanças menores ajustei alguns espaçamentos e mudei o texto do botão de "Subscribe" para "Assinar"

![Visualização tela inicial](https://user-images.githubusercontent.com/23534028/87351327-a7f1d500-c52f-11ea-870b-93b14ac909b0.png)

![Visualização sidebar comunidades](https://user-images.githubusercontent.com/23534028/87351410-c5bf3a00-c52f-11ea-8899-08731fac4821.png)

Alguns pontos em relação ao setup do ambiente, no banco de dados fornecido a conta de admin não está com permissões de admin, apenas de subscriber e no docker-compose é utilizado a variável de ambiente ${PWD} que não funciona quando o compose é rodado com sudo, já que a tabela de variáveis de ambiente é diferente. É uma situação bem específica mas achei que vale a pena comentar.

Eu não consegui carregar o css do Integral com [essas linhas do functions](https://github.com/Zero40/zero40-wordpress-theme/blob/dev/functions.php#L48) comentadas, mas sendo meu primeiro contato com o wordpress posso ter pulado algo.

No arquivo de estilo existem [várias declarações sobre newsletter](https://github.com/Zero40/zero40-wordpress-theme/blob/dev/style.css#L208) que acredito não estarem sendo utilizadas, podendo ser removidas.

Posso subir meu código pra uma branch nova, caso queira dar uma olhada.

**Comment by TiagoGouvea** [comment]
Ótimo @fernando-sa!

O checkbox, normalmente fica ao lado do texto né?
- [ ] Tipo assim

Consegue fazer este ajuste?

**Comment by fernando-sa** [comment]
Ajustado!

![tela inicial](https://user-images.githubusercontent.com/23534028/87825051-c9fb9800-c84c-11ea-879f-8b7764e5e8a0.png)

![comunidades](https://user-images.githubusercontent.com/23534028/87825116-e5ff3980-c84c-11ea-8893-7d70889585c7.png)

**Comment by TiagoGouvea** [comment]
Excelente @fernando-sa! Consegue abrir um PR com as modificações?

**Comment by fernando-sa** [comment]
Tava pensando em subir uma branch nova relacionada a issue e fazer o PR. Tem como dar as permissões?

**Comment by TiagoGouvea** [comment]
Do seu fork você poderia abrir um PR para o repo original, mas, te convidei para fazer parte da organização aqui, dai você terá a permissão direto aqui no repo.

**Comment by fernando-sa** [comment]
PR feito :)

**Comment by TiagoGouvea** [comment]
Exelente @fernando-sa ! Aceitei o PR e vou publicar no site nesta semana ainda. Muito obrigado pelo seu apoio!
